// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/NetLibR.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// MWM_hungarian
mat MWM_hungarian(mat& G);
RcppExport SEXP _NetLibR_MWM_hungarian(SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(MWM_hungarian(G));
    return rcpp_result_gen;
END_RCPP
}
// MWM_rank1
umat MWM_rank1(vec u, vec v, double u_threshold, double v_threshold);
RcppExport SEXP _NetLibR_MWM_rank1(SEXP uSEXP, SEXP vSEXP, SEXP u_thresholdSEXP, SEXP v_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type u_threshold(u_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type v_threshold(v_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(MWM_rank1(u, v, u_threshold, v_threshold));
    return rcpp_result_gen;
END_RCPP
}
// buildAdaptiveNet_fromDist
List buildAdaptiveNet_fromDist(mat& D, int max_kNN, double LC, int sym_method, int thread_no, int dist_type, double sigma);
RcppExport SEXP _NetLibR_buildAdaptiveNet_fromDist(SEXP DSEXP, SEXP max_kNNSEXP, SEXP LCSEXP, SEXP sym_methodSEXP, SEXP thread_noSEXP, SEXP dist_typeSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type max_kNN(max_kNNSEXP);
    Rcpp::traits::input_parameter< double >::type LC(LCSEXP);
    Rcpp::traits::input_parameter< int >::type sym_method(sym_methodSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< int >::type dist_type(dist_typeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(buildAdaptiveNet_fromDist(D, max_kNN, LC, sym_method, thread_no, dist_type, sigma));
    return rcpp_result_gen;
END_RCPP
}
// buildAdaptiveNet_fromEdgeList
List buildAdaptiveNet_fromEdgeList(mat& dist, mat& idx, int max_kNN, double LC, int sym_method, int thread_no, int dist_type, double sigma);
RcppExport SEXP _NetLibR_buildAdaptiveNet_fromEdgeList(SEXP distSEXP, SEXP idxSEXP, SEXP max_kNNSEXP, SEXP LCSEXP, SEXP sym_methodSEXP, SEXP thread_noSEXP, SEXP dist_typeSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< mat& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type max_kNN(max_kNNSEXP);
    Rcpp::traits::input_parameter< double >::type LC(LCSEXP);
    Rcpp::traits::input_parameter< int >::type sym_method(sym_methodSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< int >::type dist_type(dist_typeSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(buildAdaptiveNet_fromEdgeList(dist, idx, max_kNN, LC, sym_method, thread_no, dist_type, sigma));
    return rcpp_result_gen;
END_RCPP
}
// make_spanner
sp_mat make_spanner(sp_mat& G_adj, int k);
RcppExport SEXP _NetLibR_make_spanner(SEXP G_adjSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat& >::type G_adj(G_adjSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(make_spanner(G_adj, k));
    return rcpp_result_gen;
END_RCPP
}
// netAlign
sp_mat netAlign(sp_mat A, sp_mat B, sp_mat L, double alpha, double beta, double gamma, int maxiter, bool finalize);
RcppExport SEXP _NetLibR_netAlign(SEXP ASEXP, SEXP BSEXP, SEXP LSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP maxiterSEXP, SEXP finalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< sp_mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< sp_mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type finalize(finalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(netAlign(A, B, L, alpha, beta, gamma, maxiter, finalize));
    return rcpp_result_gen;
END_RCPP
}
// PCSF
sp_mat PCSF(sp_mat& Adj, vec node_scores, double kappa, int root, int clusters, int convert_similarity_to_distance);
RcppExport SEXP _NetLibR_PCSF(SEXP AdjSEXP, SEXP node_scoresSEXP, SEXP kappaSEXP, SEXP rootSEXP, SEXP clustersSEXP, SEXP convert_similarity_to_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat& >::type Adj(AdjSEXP);
    Rcpp::traits::input_parameter< vec >::type node_scores(node_scoresSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< int >::type root(rootSEXP);
    Rcpp::traits::input_parameter< int >::type clusters(clustersSEXP);
    Rcpp::traits::input_parameter< int >::type convert_similarity_to_distance(convert_similarity_to_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(PCSF(Adj, node_scores, kappa, root, clusters, convert_similarity_to_distance));
    return rcpp_result_gen;
END_RCPP
}
// batchPR
mat batchPR(sp_mat& G, mat& U, double alpha, int thread_no, double tol);
RcppExport SEXP _NetLibR_batchPR(SEXP GSEXP, SEXP USEXP, SEXP alphaSEXP, SEXP thread_noSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(batchPR(G, U, alpha, thread_no, tol));
    return rcpp_result_gen;
END_RCPP
}
// zoned_diffusion
mat zoned_diffusion(sp_mat& G, uvec& zones, mat& U, double alpha, int thread_no, double tol);
RcppExport SEXP _NetLibR_zoned_diffusion(SEXP GSEXP, SEXP zonesSEXP, SEXP USEXP, SEXP alphaSEXP, SEXP thread_noSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< uvec& >::type zones(zonesSEXP);
    Rcpp::traits::input_parameter< mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type thread_no(thread_noSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(zoned_diffusion(G, zones, U, alpha, thread_no, tol));
    return rcpp_result_gen;
END_RCPP
}
// sweepcut
vec sweepcut(sp_mat& A, vec s);
RcppExport SEXP _NetLibR_sweepcut(SEXP ASEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< vec >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(sweepcut(A, s));
    return rcpp_result_gen;
END_RCPP
}
// signed_cluster
vec signed_cluster(sp_mat A, double resolution_parameter, int seed, Nullable<IntegerVector> initial_clusters_);
RcppExport SEXP _NetLibR_signed_cluster(SEXP ASEXP, SEXP resolution_parameterSEXP, SEXP seedSEXP, SEXP initial_clusters_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type resolution_parameter(resolution_parameterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type initial_clusters_(initial_clusters_SEXP);
    rcpp_result_gen = Rcpp::wrap(signed_cluster(A, resolution_parameter, seed, initial_clusters_));
    return rcpp_result_gen;
END_RCPP
}
// unsigned_cluster
vec unsigned_cluster(sp_mat A, double resolution_parameter, int seed, Nullable<IntegerVector> initial_clusters_);
RcppExport SEXP _NetLibR_unsigned_cluster(SEXP ASEXP, SEXP resolution_parameterSEXP, SEXP seedSEXP, SEXP initial_clusters_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type resolution_parameter(resolution_parameterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type initial_clusters_(initial_clusters_SEXP);
    rcpp_result_gen = Rcpp::wrap(unsigned_cluster(A, resolution_parameter, seed, initial_clusters_));
    return rcpp_result_gen;
END_RCPP
}
// computeAutocorrelation_Geary
List computeAutocorrelation_Geary(sp_mat& G, mat& scores, int rand_perm, int num_shuffles);
RcppExport SEXP _NetLibR_computeAutocorrelation_Geary(SEXP GSEXP, SEXP scoresSEXP, SEXP rand_permSEXP, SEXP num_shufflesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< sp_mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< int >::type rand_perm(rand_permSEXP);
    Rcpp::traits::input_parameter< int >::type num_shuffles(num_shufflesSEXP);
    rcpp_result_gen = Rcpp::wrap(computeAutocorrelation_Geary(G, scores, rand_perm, num_shuffles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NetLibR_MWM_hungarian", (DL_FUNC) &_NetLibR_MWM_hungarian, 1},
    {"_NetLibR_MWM_rank1", (DL_FUNC) &_NetLibR_MWM_rank1, 4},
    {"_NetLibR_buildAdaptiveNet_fromDist", (DL_FUNC) &_NetLibR_buildAdaptiveNet_fromDist, 7},
    {"_NetLibR_buildAdaptiveNet_fromEdgeList", (DL_FUNC) &_NetLibR_buildAdaptiveNet_fromEdgeList, 8},
    {"_NetLibR_make_spanner", (DL_FUNC) &_NetLibR_make_spanner, 2},
    {"_NetLibR_netAlign", (DL_FUNC) &_NetLibR_netAlign, 8},
    {"_NetLibR_PCSF", (DL_FUNC) &_NetLibR_PCSF, 6},
    {"_NetLibR_batchPR", (DL_FUNC) &_NetLibR_batchPR, 5},
    {"_NetLibR_zoned_diffusion", (DL_FUNC) &_NetLibR_zoned_diffusion, 6},
    {"_NetLibR_sweepcut", (DL_FUNC) &_NetLibR_sweepcut, 2},
    {"_NetLibR_signed_cluster", (DL_FUNC) &_NetLibR_signed_cluster, 4},
    {"_NetLibR_unsigned_cluster", (DL_FUNC) &_NetLibR_unsigned_cluster, 4},
    {"_NetLibR_computeAutocorrelation_Geary", (DL_FUNC) &_NetLibR_computeAutocorrelation_Geary, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_NetLibR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
