# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call(`_NetLibR_set_seed`, seed))
}

MWM_hungarian <- function(G) {
    .Call(`_NetLibR_MWM_hungarian`, G)
}

MWM_rank1 <- function(u, v, u_threshold = 0, v_threshold = 0) {
    .Call(`_NetLibR_MWM_rank1`, u, v, u_threshold, v_threshold)
}

signed_cluster <- function(A, resolution_parameter = 1.0, seed = 0L, initial_clusters_ = NULL) {
    .Call(`_NetLibR_signed_cluster`, A, resolution_parameter, seed, initial_clusters_)
}

unsigned_cluster <- function(A, resolution_parameter = 1.0, seed = 0L, initial_clusters_ = NULL) {
    .Call(`_NetLibR_unsigned_cluster`, A, resolution_parameter, seed, initial_clusters_)
}

bmatching <- function(A, b_limit, seed = 0L) {
    .Call(`_NetLibR_bmatching`, A, b_limit, seed)
}

make_spanner <- function(G_adj, k) {
    .Call(`_NetLibR_make_spanner`, G_adj, k)
}

netAlign <- function(A, B, L, alpha = 1.0, beta = 1.0, gamma = 0.99, maxiter = 100L, finalize = FALSE) {
    .Call(`_NetLibR_netAlign`, A, B, L, alpha, beta, gamma, maxiter, finalize)
}

PCSF <- function(Adj, node_scores, kappa = 1.0, root = -1L, clusters = 20L, convert_similarity_to_distance = 0L) {
    .Call(`_NetLibR_PCSF`, Adj, node_scores, kappa, root, clusters, convert_similarity_to_distance)
}

computeAutocorrelation_Geary <- function(G, scores, rand_perm = 100L, num_shuffles = 10000L) {
    .Call(`_NetLibR_computeAutocorrelation_Geary`, G, scores, rand_perm, num_shuffles)
}

