# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call(`_NetLibR_set_seed`, seed))
}

MWM_hungarian <- function(G) {
    .Call(`_NetLibR_MWM_hungarian`, G)
}

MWM_rank1 <- function(u, v, u_threshold = 0, v_threshold = 0) {
    .Call(`_NetLibR_MWM_rank1`, u, v, u_threshold, v_threshold)
}

signed_cluster <- function(A, resolution_parameter = 1.0, seed = 0L, initial_clusters_ = NULL) {
    .Call(`_NetLibR_signed_cluster`, A, resolution_parameter, seed, initial_clusters_)
}

unsigned_cluster <- function(A, resolution_parameter = 1.0, seed = 0L, initial_clusters_ = NULL) {
    .Call(`_NetLibR_unsigned_cluster`, A, resolution_parameter, seed, initial_clusters_)
}

